import './globals.css';
import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { Header, Footer, ModalAddTodo, ModalEditTodo } from '@/components';
import GlobalState from './providers';

const inter = Montserrat({ subsets: ['cyrillic'] });

export const metadata: Metadata = {
  title: 'Roman Fedorov | Todos TS + Next.js',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='ru'>
      <body className={`${inter.className} custom-body`}>
        <GlobalState>
          <ModalAddTodo />
          <Header />
          {children}
          <Footer />
          <ModalEditTodo />
        </GlobalState>
      </body>
    </html>
  );
}
