import './globals.css';
import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import Modals from '@/components/Modals/Modals';
import { Header, Footer } from '@/components';
import GlobalState from './providers';
import { ToastContainer } from 'react-toastify';

const inter = Montserrat({ subsets: ['cyrillic'] });

export const metadata: Metadata = {
  title: 'Todos TS + Next.js | Roman Fedorov',
  description: 'Generated by Next.js | TailwindCSS | TypeScript',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='ru'>
      <body className={`${inter.className} custom-body`}>
        <GlobalState>
          <Modals />
          <Header />
          {children}
          <Footer />
          <ToastContainer />
        </GlobalState>
      </body>
    </html>
  );
}
